 1.Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’


In [1]:
#1
import numpy as np

def foo_1(arr, target):
    indices = np.argsort(np.abs(arr - target)) 
    if arr[indices[0]] == target:
        return indices
    else:
        return 'no item found'
arr1 = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 101])
target1 = 7
output1 = foo_1(arr1, target1)
print(output1)



[2 3 4 5 6 8 1 7 0 9]


In [2]:
arr2 = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 101])
target2 = 11
output2 = foo_1(arr2, target2)
print(output2)

no item found


3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.


In [7]:
#3.1
data = np.array([[85, 89, 88],
                 [78, 89, 94],
                 [91, 87, 90],
                 [87, 95, 84]])

above_90 = data[(data > 90).any(axis=1)]
print(above_90)

[[78 89 94]
 [91 87 90]
 [87 95 84]]


3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.


In [8]:
#3.2
data = np.array([[120, 150, 130, 110],
                 [200, 180, 220, 250],
                 [90, 100, 95, 110],
                 [300, 280, 320, 340]])
mean_values = np.mean(data, axis=1)
median_values = np.median(data, axis=1)
std_dev_values = np.std(data, axis=1)
max_month_indices = np.argmax(data, axis=1)

print("Mean values:", mean_values)
print("Median values:", median_values)
print("Standard deviation values:", std_dev_values)
print("Month with the highest sales:", max_month_indices)


Mean values: [127.5  212.5   98.75 310.  ]
Median values: [125.  210.   97.5 310. ]
Standard deviation values: [14.79019946 25.86020108  7.39509973 22.36067977]
Month with the highest sales: [1 3 3 3]


3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.


In [9]:
#3.3
random_array = np.random.randint(1, 101, size=1000)
top_10_values, top_10_counts = np.unique(random_array, return_counts=True)
sorted_indices = np.argsort(top_10_counts)[::-1]
result = top_10_values[sorted_indices[:10]]

print("Top 10 most frequently occurring values:", result)


Top 10 most frequently occurring values: [ 1 69 64 91 88  7 18 56 98 30]


2. Write a user defined function foo_2 that takes a 1 or 2 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.
